#!./expect -- 
set timeout 120 
#log_user 0

set SERVER [lindex $argv 0]
set MWS [lindex $argv 1]
set MWS_ROOTPW [lindex $argv 2]
spawn ssh -ostricthostkeychecking=no root@$MWS
expect -timeout 10 "Are you sure you want to continue connecting" {send "yes\r"; exp_continue}
expect "Password:"
send "$MWS_ROOTPW\r"
expect "\/#"
sleep 2
	send -- "/ericsson/jumpstart/bin/manage_pks_rootcerts.bsh -a add -r /JUMP/MWS_add_client_files/rootcer/rootca.cer.$SERVER\r"
	expect "Enter the Fully Qualified Host Name for the LDAP Server"
	send -- "$SERVER\r"
	expect "Enter the IP address of the LDAP server that this certificate authenticates"
	send -- "\r"
expect -timeout 30 "Do you want to configure a secondary LDAP server?" {send "No\r"; exp_continue}
expect -timeout 30 "Are you sure you wish to add the rootcert specified?" {send "Yes\r"; exp_continue}
sleep 10
send "exit\r"
catch "wait -i $spawn_id" reason

# return status code of spawned process
exit [ lindex $reason 3 ]

