#!./expect -- 

#Return 1 if serious problem don't continue
#Return 2 no mirrors defined, do nothing proceed with upgrade
#Return 3 in sync, do nothing proceed with upgrade
#Return 4 boot from detach and sync

set timeout 120 
#log_user 0

set SERVER [lindex $argv 0]
set results(DEFINED) "1"
set results(INSYNC) "1"
set results(WARNING) "0"
set results(SMTOOL) "0"
set results(INSTALL) "0"
set D1 "\$1" 
set D2 "\$2" 
set D "\$" 
set PIPESTATUS "\${PIPESTATUS\[0\]}" 
set FILTER "\[\{,\},\"\]" 

#main

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@$SERVER.athtem.eei.ericsson.se
#exp_internal 1
set timeout 30
while 1 {
	expect {
		"Are you sure you want to continue connecting" {
			send "yes\r"}
		"login: " {
			send "root\r"}

		"Password:" {
			send "shroot\r"
			break}
		eof {
			puts "warning: timed out"

			exit 1}
 		timeout {
			puts "warning: timed out"
			exit 1}
		}
	}


expect "#"
set timeout 10800

send -- "/ericsson/dmr/bin/dmtool de b\r"
expect "Continue (y/n) or more (h)help"
send -- "y\r"
while 1 {
        expect {
                "Do you wish to reboot the system now" {
                        send "y\r"}
                "Use _m2 snapshots (y/n)?" {
                        send "y\r"}
		"Force reboot (y/n)?" {
                        send "y\r"}
                eof {
                        exit 0}
                timeout {
                        exit 0}
                }
        }

