#!./expect -- 
set timeout 120 

set ADMIN1 [lindex $argv 0]
set ADMIN2 [lindex $argv 1]
set OMPATH [lindex $argv 2]
set SOLARISPATH [lindex $argv 3]
set CHECK [lindex $argv 4]
set MWSIP [lindex $argv 5]
set NEWD [lindex $argv 6]


#main
spawn ssh -ostricthostkeychecking=no root@${ADMIN1}.athtem.eei.ericsson.se
#exp_internal 1
while 1 {
        expect {
                "Are you sure you want to continue connecting" {
                        send "yes\r"}
                "login: " {
                        send "root\r"}

                "Password:" {
                        send "shroot\r"
                        break}
                eof {
                        puts "warning: timed out"

                        exit 1}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }
expect "#"

                
