#!./expect -- 
set force_conservative 1
#exp_internal 1

set release [lindex $argv 0]
set shipment [lindex $argv 1]
set mws [lindex $argv 2]
set mws_rootpw [lindex $argv 3]

set timeout 3600
expect_after timeout exit
spawn ssh -ostricthostkeychecking=no root@$mws

while 1 {
        expect {
                "Are you sure you want to continue connecting" {
                        send "yes\r"}
                "login: " {
                        send "root\r"}

                "Password:" {
                        send "$mws_rootpw\r"
                        break}
                eof {
                        puts "warning: timed out"
                        exit 1}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }


expect "\/#"
sleep 2
send -- "bash\r"
expect "#"
send -- "chmod -R a+rw /export/SW_LOCATION/OSSRC_MEDIA/OSSRC_${release}/${shipment}\r"
expect "#"
send -- "chmod -R a+rw /export/SW_LOCATION/OSSRC_MEDIA/OSSRC_${release}/${shipment}_UG\r"
expect "#"
send -- "chmod -R a+rw /export/jumpstart/teams/OSSRC_${release}/${shipment}\r"
expect "#"
sleep 5
