#!./expect -- 

set timeout 120 

set livenode [lindex $argv 0]
set upgnode [lindex $argv 1]

#main

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@$livenode.athtem.eei.ericsson.se
#exp_internal 1
while 1 {
	expect {
		"Are you sure you want to continue connecting" {
			send "yes\r"}
		"login: " {
			send "root\r"}

		"Password:" {
			send "shroot\r"
			break}
		eof {
			puts "warning: timed out"

			exit 1}
 		timeout {
			puts "warning: timed out"
			exit 1}
		}
	}


expect "#"

 send "ssh ${upgnode}-priv\r"
while 1 {
        expect {
                "${upgnode}\{root\} #" {
                        break}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }

set timeout 120 
set count 0
while {$count < 15} {
		send "hastatus -sum | grep \"Oss \"| grep ${upgnode} | grep -v \"W_\"\r"

		expect {
                	" ONLINE" {
			expect "#"
                        sleep 5
                        exit 0}

                timeout {
			puts "timeout"
                        set count [expr $count+1]}
                }
}
exit 1
