#!./expect -- 

set timeout 120 

set ADMIN1 [lindex $argv 0]
set ADMIN2 [lindex $argv 1]
set D "\$" 

#main

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@$ADMIN1.athtem.eei.ericsson.se
#exp_internal 1
while 1 {
	expect {
		"Are you sure you want to continue connecting" {
			send "yes\r"}
		"login: " {
			send "root\r"}

		"Password:" {
			send "shroot\r"
			break}
		eof {
			puts "warning: timed out"

			exit 1}
 		timeout {
			puts "warning: timed out"
			exit 1}
		}
	}


expect "#"

 send "ssh ${ADMIN2}-priv\r"
while 1 {
        expect {
                "${ADMIN2}\{root\} #" {
                        break}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }

send "hastatus -sum | grep  \" ONLINE \" | wc -l | sed -e 's/^\[ \\t]*//' | sed 's/\[ \\t]*$D//'\r"
        expect "#"
        set f1 $expect_out(buffer)
        set f2 [split $f1 "\r\n"]
        if {[lindex $f2 2] == "8"} {
		exit 0
        }
        if {[lindex $f2 2] == "9"} {
                exit 0
        }

exit 1
