set force_conservative 1
set timeout -1
set machine [lindex $argv 0]
set core [lindex $argv 4]
set gran [lindex $argv 5]
set wran [lindex $argv 6]
set option [lindex $argv 7]
set cifip [lindex $argv 8]
set mws [ lindex $argv 9]
set timeout 5400
spawn /net/attembak3.athtem.eei.ericsson.se/adisk/sfw/scripts/console/conn.sh -s [lindex $argv 0] -i [lindex $argv 3]
set main_spawn_id $spawn_id
expect "Connected to" 
send "\r\r"
expect -timeout 10 "login" {send "root\r"; exp_continue}
expect -timeout 10 "Password" {send "shroot\r"; exp_continue}
expect -timeout 10 "#" {send "sync;sync;halt\r"; exp_continue}
expect_after timeout exit
expect "ok"
exec sleep 5
if { $option == "YES" } { 
	send "boot net:dhcp - install inst_type=ossrc config=system ossrc_sw_locate=[lindex $argv 1] om_sw_locate=[lindex $argv 1] rmirr label_disks\r"
} else {
	send "boot net:dhcp - install inst_type=ossrc config=system ossrc_sw_locate=[lindex $argv 1] om_sw_locate=[lindex $argv 1] label_disks\r"
}
set timeout 3600
while 1 {
expect {
 "Please Specify the exact location of preinirate file"
        {
                spawn ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no root@$machine.athtem.eei.ericsson.se
                while 1 {
                        expect {
                                "assword" {
                                        send "shroot\r"
                                        break }
                                timeout        {exit 1}
                                }
                        }
                expect "#"
                send " cp /net/$mws/JUMP/MWS_add_client_files/preinirate_$machine /tmp/ \r"
                expect "#"
                send "exit\r"
                expect "closed"
                set spawn_id $main_spawn_id
                send "/tmp/ \r"
                expect "\r"      
                set timeout 24600
        }
 "Successfully executed core" {break}
 timeout        {exit 1}
 }
}
exec sleep 600
send "exit\r"
