#!./expect -- 


set timeout 120 
#log_user 0

set LIVEnode [lindex $argv 0].athtem.eei.ericsson.se

#main

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@$LIVEnode
#exp_internal 1
expect_after timeout exit
set timeout 60
while 1 {
        expect {
                "Are you sure you want to continue connecting" {
                        send "yes\r"}
                "login: " {
                        send "root\r"}

                "Password:" {
                        send "shroot\r"
                        break}
                eof {
                        puts "warning: timed out"

                        exit 1}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }
expect "#"
send "/opt/ericsson/sck/bin/split_cluster unblock_disk_access\r"
expect {
	"No disks to unblock on" {
		puts "WARNING:Disks already unblocked, continuing..."}
	"#" {
		puts "Unblocking disks completed."
		sleep 180}
}
exit 0
