set force_conservative 1
set ADMIN1 [lindex $argv 0]
set UGBUIP [lindex $argv 1]
set MWS_HOSTNAME [lindex $argv 2]
set MWS_ROOTPW [lindex $argv 3]
set timeout 54

spawn telnet $MWS_HOSTNAME
expect "login:"
send "root\r"
expect "assword:"
send "$MWS_ROOTPW\r"
expect "#"
send "ssh ${UGBUIP}\r"
while 1 {
expect {
 "Are you sure you want to continue connecting" {send "yes\r"}
 "assword" {
                send "shroot\r"
                break }
 timeout        {exit 1}
 }
}
expect "#"
puts "connecting to admin1"
 send "ssh ${ADMIN1}-priv\r"
while 1 {
        expect {
                "${ADMIN1}\{root\} #" {
                        break}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }
set timeout  180
expect "#"
send "/opt/ericsson/nms_cif_sm/bin/smtool -offline fth_bootstrap -reason=upgrade -reasontext=upgrade\r"
expect "#"
sleep 30
send "/opt/ericsson/nms_cif_sm/bin/smtool -offline fth_1 -reason=upgrade -reasontext=upgrade\r"
expect "#"
sleep 30
