#!./expect -- 


set timeout 120 
#log_user 0

set ADMIN1 [lindex $argv 0]

#main

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@$ADMIN1.athtem.eei.ericsson.se
#exp_internal 1
expect_after timeout exit
set timeout 60
while 1 {
        expect {
                "Are you sure you want to continue connecting" {
                        send "yes\r"}
                "login: " {
                        send "root\r"}

                "Password:" {
                        send "shroot\r"
                        break}
                eof {
                        puts "warning: timed out"

                        exit 1}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }
expect "#"
send "/opt/ericsson/sck/bin/split_cluster unblock_disk_access\r"
expect "#"
sleep 180 
exit 0
