set force_conservative 1
set server [lindex $argv 0]
set ilom [lindex $argv 1]
set prompt "^.*-> $"
set prompt_dm "> $"
set state 0
set timeout 5400

spawn /usr/bin/telnet atrcx1089.athtem.eei.ericsson.se
expect "login:"
send "root\r"
expect "assword:"
send "dmbld23\r"
expect "#"
send "bash\r"
expect "#"
send "ssh root@$ilom\r"
while 1 {
expect {
 "Are you sure you want to continue connecting" {send "yes\r"}
 "assword" {
                send "shroot12\r"
                break }
 timeout        {exit 1}
 }
}
expect -re $prompt
send "set /system1/oemhp_power1 oemhp_powerreg=max\r"
expect -re $prompt
sleep 20

