#!./expect -- 

set timeout 120 
#log_user 0

set ADMIN1 [lindex $argv 0]
set ADMIN2 [lindex $argv 1]

set OMPATH [lindex $argv 2]
set SOLARISPATH [lindex $argv 3]
set CHECK [lindex $argv 4]
set MWSIP [lindex $argv 5]
set d1 "\$1" 
set d2 "\$2"
set d3 "\$3"
set d4 "\$4"

#main

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@${ADMIN1}.athtem.eei.ericsson.se
#exp_internal 1
while 1 {
	expect {
		"Are you sure you want to continue connecting" {
			send "yes\r"}
		"login: " {
			send "root\r"}

		"Password:" {
			send "shroot\r"
			break}
		eof {
			puts "warning: timed out"

			exit 1}
 		timeout {
			puts "warning: timed out"
			exit 1}
		}
	}
expect "#"
expect_after timeout exit
set timeout 3600 
if {$ADMIN2 != "NO"} {
	send "ssh ${ADMIN2}-priv\r"
	expect "${ADMIN2}\{root\} #"
}
send -- "svcs -a |grep \"iscsi/initiator\"|grep aintenance && svcadm clear svc:/network/iscsi/initiator:default\r"
expect " #"
send -- "mkdir -p /var/tmp/OM\r"
expect " #"
send -- "umount -f /var/tmp/OM > /dev/null 2>&1\r"
expect " #"
send -- "mount ${MWSIP}:${OMPATH} /var/tmp/OM\r"
expect " #"	
send -- "/var/tmp/OM/omtools/upgrade_om.bsh -p /var/tmp/OM -a all\r"
while 1 {
        expect  {
                "Finished OM Software Upgrade" {
                        break}
                eof {         
                        puts "warning: timed out"
                                
                        exit 1}
                timeout {       
                        puts "warning: timed out"
                        exit 1}
                }
        }        

expect " #"	
send -- "umount -f /var/tmp/OM > /dev/null 2>&1\r"
expect " #"	
send "exit\r"
exit 0


