#!./expect -- 


set timeout 120 
#log_user 0

set SERVER [lindex $argv 0]
set ADMIN2 [lindex $argv 1]

#main

spawn ssh -ostricthostkeychecking=no root@$SERVER.athtem.eei.ericsson.se
#exp_internal 1
expect_after timeout exit
set timeout 60
while 1 {
        expect {
                "Are you sure you want to continue connecting" {
                        send "yes\r"}
                "login: " {
                        send "root\r"}

                "Password:" {
                        send "shroot\r"
                        break}
                eof {
                        puts "warning: timed out"

                        exit 1}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }
expect "#"
send "ssh ${ADMIN2}-priv\r"
expect "${ADMIN2}\{root\}"
sleep 5
send "/opt/ericsson/sck/bin/system_checks.bsh -c pre_oss_upgrade\r"

while 1 {
        expect {
                "No failed Pre Checks detected" {
                        sleep 10
                        break}
                "One or more Pre Checks Failed" {
                        sleep 10
                        exit 1}
                eof {
                        puts "warning: timed out"
                        exit 1}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }

send "exir\r"; expect "logout"
send "exir\r"; expect "logout"

