#!./expect -- 


set timeout 120 
#log_user 0

set SERVER [lindex $argv 0]

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@$SERVER.athtem.eei.ericsson.se
#exp_internal 1
set timeout 600
while 1 {
	expect {
		"Are you sure you want to continue connecting" {
			send "yes\r"}

		"Password:" {
			send "shroot\r"
			break}
		eof {
			puts "warning: timed out"

			exit 1}
 		timeout {
			puts "warning: timed out"
			exit 1}
		}
	}


expect "#"
send "/opt/ericsson/sck/bin/system_upgrade_utils.bsh -v Set_default 1 1 1 1 1 0\r"
expect "#"
