#!./expect -- 


set timeout 6200 
#log_user 0

set SERVER [lindex $argv 0]

#main

spawn ssh -oUserKnownHostsFile=/dev/null -ostricthostkeychecking=no root@$SERVER.athtem.eei.ericsson.se
#exp_internal 1
set timeout 30
while 1 {
	expect {
		"Are you sure you want to continue connecting" {
			send "yes\r"}
		"login: " {
			send "root\r"}

		"Password:" {
			send "shroot\r"
			break}
		eof {
			puts "warning: timed out"

			exit 1}
 		timeout {
			puts "warning: timed out"
			exit 1}
		}
	}
set timeout 6200 
expect "#"
send "/opt/ericsson/sck/bin/split_cluster\r"
expect "(y/n)"
send "y\r"
while 1 {
        expect {
		"Password:" {
			send "shroot\r"}
                "Split Cluster completed" {
                        sleep 5
			break}
                timeout {
                        puts "warning: timed out"
                        exit 1}
                }
        }

