#!/usr/local/bin/expect

set timeout 5
set server [lindex $argv 0]
set newpwd [lindex $argv 1]
set prompt "\[>%\\$#\] "

# Mission of this Script is to set the passwords

send_user "connecting to $server on port 22\n"
spawn ssh root@$server 
 
expect {
    -re "$prompt" {
        send_user " (changing password at prompt)\n"
        send "passwd\n" 
        expect {
                    -re "\[nN\]ew \[pP\]assword:|\[nN\]ew \[pP\]assword \[aA\]gain:" {
						send_user "\n ====DETECTED=====: First Prompted for new Password\n"
                        send "$newpwd\n" 
                        expect {
                            "between changes." {
                                send_user "\nPassword change failed.\n"
                                exit 1
                            }
                            -re "\[nN\]ew \[pP\]assword:|\[nN\]ew \[pP\]assword \[aA\]gain:" {
								send_user "\n ====DETECTED=====: Second Prompted for new Password\n"
                                send "$newpwd\n" 
                                expect {
                                    -re "$prompt" { 
                                        send_user "\n ====DETECTED=====: return to shell command prompt\n"
										send_user "\nPassword successfully changed root@$server to: $newpwd\n"
                                        exit 0
                                    }
                                    default {
                                        send_user "\nPassword change failed.\n"
                                        exit 1
                                    }
									eof {send_user "eof detected - end of loop\r"; exit 99}
									timeout {send_user "timeout detected - end of loop\r"; exit 99}
                                }
                            }
                            "BAD PASSWORD" {
                                send_user "\nPassword change failed.\n"
                                exit 1
                            }
                            default {
                                send_user "\nPassword change failed.\n"
                                exit 1
                            }
							eof {send_user "eof detected - end of loop\r"; exit 99}
							timeout {send_user "timeout detected - end of loop\r"; exit 99}
                        }
                    }
                    default {
                        send_user "\nPassword change failed.\n"
                        exit 1
                    }
				eof {send_user "eof detected - end of loop\r"; exit 99}
				timeout {send_user "timeout detected - end of loop\r"; exit 99}
                }
        }
    }
    default {
        send_user "\nAutomated login failed.\n"
        exit 1
    }
}
 