#!/usr/local/bin/expect
#exp_internal 2
set timeout 5
set server [lindex $argv 0]
set newpwd [lindex $argv 1]
set prompt "\[>%\\$#\] "

# Mission of this Script is to set the passwords

send_user "====================================\n"
send_user "EXPECT: connecting to $server on port 22 changing root password to: $newpwd\n"
send_user "====================================\n"
spawn ssh root@$server 
 
expect {
    -re "$prompt" {
        send_user "\t(changing password at prompt)\n"
        send "passwd\n" 
        expect {
                    -re "\[nN\]ew \[pP\]assword:|\[nN\]ew \[pP\]assword \[aA\]gain:" {
						send_user "\n\t====DETECTED=====: First Prompted for new Password\n"
						send -- "$newpwd\n" 
                        expect {
                            "between changes." {
                                send_user "\nPassword change failed.\n"
                                exit 1
                            }
                            -re "\[nN\]ew \[pP\]assword:|\[nN\]ew \[pP\]assword \[aA\]gain:" {
								send_user "\n\t====DETECTED=====: Second Prompted for new Password\n"
								send -- "$newpwd\n" 
                                expect {
                                    -re "$prompt" { 
                                        send_user "\n\t====DETECTED=====: return to shell command prompt\n"
										send_user "\n\tPassword successfully changed root@$server to: $newpwd\n"
										send_user "====================================\n"
										send_user "SUCESS:\n"
										send_user "====================================\n"
                                        exit 0
										
                                    }
                                    default {
                                        send_user "\n\tPassword change failed.\n"
                                        exit 1
                                    }
									eof {send_user "eof detected - end of loop\r"; exit 99}
									timeout {send_user "timeout detected - end of loop\r"; exit 99}
                                }
                            }
                            "BAD PASSWORD" {
                                send_user "\n\tPassword change failed.\n"
                                exit 1
                            }
                            default {
                                send_user "\n\tnPassword change failed.\n"
                                exit 1
                            }
							eof {send_user "eof detected - end of loop\r"; exit 99}
							timeout {send_user "timeout detected - end of loop\r"; exit 99}
                        }
                    }
                    default {
                        send_user "\n\tPassword change failed.\n"
                        exit 1
                    }
				eof {send_user "eof detected - end of loop\r"; exit 99}
				timeout {send_user "timeout detected - end of loop\r"; exit 99}
                }
        }
    }
    default {
        send_user "\n\tAutomated login failed.\n"
        exit 1
    }
}
 