#!/usr/local/bin/expect

set O_INPFILE [lindex $argv 0]

set timeout 30

spawn su - orcha -c "/ericsson/orchestrator/bin/setup_orcha_user.bsh -n -f $O_INPFILE"

expect {
    "Enter password to be used for the orcha user:" { send "Orch@12A\r" }
    eof { send_user "ERROR: Early EndOfFile\n"; exit 98}
    timeout { send_user "ERROR: Time out waiting for password prompt\n"; exit 99}
    }

expect {
    "Re-enter orcha user Password:" { send "Orch@12A\r" }
    eof { send_user "ERROR: Early EndOfFile\n"; exit 98}
    timeout { send_user "ERROR: Time out waiting for password prompt\n"; exit 99}
    }

expect {
    eof {}
    timeout { send_user "ERROR: Time out waiting for script to end\n"; exit 99}
    }

catch "wait -i $spawn_id" reason

# return status code of spawned process

exit [ lindex $reason 3 ]

